In [34]:
import pandas as pandu

df = pandu.read_csv("./data/urinalysis_tests.csv")

df.head()

,Unnamed: 0,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,0,76.0,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,1-3,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,1,9.0,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,1-3,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,2,12.0,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,3,77.0,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,5-8,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,4,29.0,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,1-4,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1436 non-null   int64
 1   Age               1436 non-null   float64
 2   Gender            1436 non-null   object
 3   Color             1435 non-null   object
 4   Transparency      1436 non-null   object
 5   Glucose           1436 non-null   object
 6   Protein           1436 non-null   object
 7   pH                1436 non-null   float64
 8   Specific Gravity  1436 non-null   float64
 9   WBC               1436 non-null   object
 10  RBC               1436 non-null   object
 11  Epithelial Cells  1436 non-null   object
 12  Mucous Threads    1436 non-null   object
 13  Amorphous Urates  1436 non-null   object
 14  Bacteria          1436 non-null   object
 15  Diagnosis         1436 non-null   object
dtypes: float64(3), int64(1), object(12)
memory usage: 179.6+ KB

In [ ]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [58]:
print(df.columns)
df.columns.tolist()

Index(['Age', 'Gender', 'Color', 'Transparency', 'Glucose', 'Protein', 'pH',
       'Specific Gravity', 'WBC', 'RBC', 'Epithelial Cells', 'Mucous Threads',
       'Amorphous Urates', 'Bacteria', 'Diagnosis'],
      dtype='object')

['Age',
 'Gender',
 'Color',
 'Transparency',
 'Glucose',
 'Protein',
 'pH',
 'Specific Gravity',
 'WBC',
 'RBC',
 'Epithelial Cells',
 'Mucous Threads',
 'Amorphous Urates',
 'Bacteria',
 'Diagnosis']

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1436 non-null   float64
 1   Gender            1436 non-null   object
 2   Color             1435 non-null   object
 3   Transparency      1436 non-null   object
 4   Glucose           1436 non-null   object
 5   Protein           1436 non-null   object
 6   pH                1436 non-null   float64
 7   Specific Gravity  1436 non-null   float64
 8   WBC               1436 non-null   object
 9   RBC               1436 non-null   object
 10  Epithelial Cells  1436 non-null   object
 11  Mucous Threads    1436 non-null   object
 12  Amorphous Urates  1436 non-null   object
 13  Bacteria          1436 non-null   object
 14  Diagnosis         1436 non-null   object
dtypes: float64(3), object(12)
memory usage: 168.4+ KB

In [27]:
print(df.isnull().sum())

Age                 0
Gender              0
Color               1
Transparency        0
Glucose             0
Protein             0
pH                  0
Specific Gravity    0
WBC                 0
RBC                 0
Epithelial Cells    0
Mucous Threads      0
Amorphous Urates    0
Bacteria            0
Diagnosis           0
dtype: int64

In [45]:
print(df[df.isnull().any(axis=1)])

       Age  Gender Color Transparency   Glucose Protein   pH  \
1353  18.0  FEMALE   NaN        CLEAR  NEGATIVE   TRACE  6.0

      Specific Gravity  WBC  RBC Epithelial Cells Mucous Threads  \
1353              1.02  1-2  0-2             RARE       MODERATE

     Amorphous Urates Bacteria Diagnosis
1353        NONE SEEN     RARE  NEGATIVE

In [32]:
df.drop(df.index[1353], inplace=True)

In [46]:
df.describe()

               Age           pH  Specific Gravity
count  1436.000000  1436.000000       1436.000000
mean     27.207521     6.052925          1.015850
std      23.460032     0.598475          0.007285
min       0.010000     5.000000          1.005000
25%       6.000000     6.000000          1.010000
50%      23.000000     6.000000          1.015000
75%      45.000000     6.500000          1.020000
max      92.000000     8.000000          1.030000

In [52]:
df[df["Age"] == 54]

,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
89,54.0,MALE,DARK YELLOW,CLEAR,3+,TRACE,6.5,1.030,2-3,0-2,FEW,PLENTY,NONE SEEN,FEW,NEGATIVE
114,54.0,FEMALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.025,2-4,3-5,FEW,MODERATE,NONE SEEN,RARE,NEGATIVE
299,54.0,FEMALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.5,1.015,3-5,0-1,FEW,MODERATE,NONE SEEN,RARE,NEGATIVE
312,54.0,MALE,LIGHT YELLOW,CLEAR,3+,NEGATIVE,5.0,1.025,0-2,0-2,RARE,FEW,NONE SEEN,FEW,NEGATIVE
463,54.0,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.030,10-16,1-3,PLENTY,FEW,NONE SEEN,FEW,NEGATIVE
1119,54.0,MALE,DARK YELLOW,CLEAR,NEGATIVE,1+,6.0,1.020,1-2,2-4,RARE,PLENTY,NONE SEEN,RARE,NEGATIVE
1189,54.0,MALE,YELLOW,CLEAR,NEGATIVE,TRACE,6.5,1.015,1-2,3-5,RARE,FEW,NONE SEEN,RARE,NEGATIVE
1193,54.0,FEMALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.020,1-3,1-3,MODERATE,FEW,NONE SEEN,FEW,NEGATIVE
1207,54.0,MALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.010,1-3,0-2,RARE,NONE SEEN,NONE SEEN,RARE,NEGATIVE
1305,54.0,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.010,0-2,0-1,RARE,NONE SEEN,NONE SEEN,RARE,NEGATIVE
1310,54.0,MALE,AMBER,CLEAR,NEGATIVE,1+,6.0,1.015,0-1,0-2,RARE,MODERATE,NONE SEEN,RARE,NEGATIVE

In [59]:
from sklearn.preprocessing import LabelEncoder

In [61]:
for column in df.columns:
    if df[column].dtype == "object":
        df[column] = LabelEncoder().fit_transform(df[column])

In [62]:
df.head()

,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,76.0,0,4,0,4,3,5.0,1.010,5,2,4,5,2,3,0
1,9.0,1,2,3,4,0,5.0,1.030,5,2,6,0,0,2,0
2,12.0,1,4,3,4,4,5.0,1.030,2,2,6,0,1,5,0
3,77.0,1,1,1,4,0,6.0,1.020,56,51,6,5,2,0,0
4,29.0,0,9,2,4,4,6.0,1.025,6,2,6,5,2,0,0

In [63]:
save_path = "./data/cleaned_urinalysis_tests.csv"
df.to_csv(save_path, index=False)